Fixed "missing env vars" for deployments. (#24)
* Fixed "missing env vars" for deployments.
- Used go framework reserved "-scheduler" service for both reject and sync.
- Added utility methods in taskfile for easier development experience
- Added *.rock to gitignore
- Added missing charm libs

* Removed specific app name mention from taskfile

* Rockcraft updates
- Bumped version to v3
- Updated README rock services mentions
- Made taskfile independent from rock version.

* Fail to load image message for task

diff --git a/taskfile.yaml b/taskfile.yaml
--- a/taskfile.yaml
+++ b/taskfile.yaml
@@ -6,6 +6,13 @@ dotenv:
 
 interval: "500ms"
 
+vars:
+  PATH_CHARM: "./charm/charm_amd64.charm"
+  IMAGE: "specs.canonical.com:latest"
+  APP_NAME: "specs"
+  ROCK:
+    sh: ls -t canonical-specs-v2_*.rock 2>/dev/null | head -1
+
 tasks:
   install_bun:
     description: "Install bun"
@@ -88,3 +95,30 @@ tasks:
     cmds:
       - echo "Building the UI..."
       - cd ui && bun install  && bun run build
+
+  # Juju tasks
+  clean-imgs:
+    desc: Clean all local images
+    cmds:
+      - microk8s ctr images list | grep 'localhost:32000/{{.APP_NAME}}' | awk '{print $1}' | xargs -r microk8s ctr images remove
+  load-img:
+    desc: Load .rock image into local registry
+    cmds:
+      - |
+        if [ -z "{{.ROCK}}" ]; then
+          echo "ERROR: image could not be loaded. Check that you have packed rock!"
+          exit 1
+        fi
+        rockcraft.skopeo --insecure-policy copy --dest-tls-verify=false oci-archive:{{.ROCK}} docker://localhost:32000/{{.IMAGE}}
+  deploy:
+    desc: Deploy the charm to microk8s
+    cmds:
+      - juju deploy {{.PATH_CHARM}} {{.APP_NAME}} --resource app-image=localhost:32000/{{.IMAGE}}
+  refresh:
+    desc: Refresh the charm in microk8s
+    cmds:
+      - juju refresh {{.APP_NAME}} --path {{.PATH_CHARM}} --resource app-image=localhost:32000/{{.IMAGE}}
+  ssh:
+    desc: SSH into the worker container
+    cmds:
+      - juju ssh --container app {{.APP_NAME}}/0 bash
