rollout to prod action

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -2,33 +2,93 @@ name: Juju deploy
 
 on:
   workflow_dispatch:
+    inputs:
+      environment:
+        description: "Target environment (Staging or Production)"
+        required: false
+        type: environment
+        default: "Production"
+      commit:
+        description: "Commit SHA"
+        required: false
+        type: string
+        default: HEAD
   push:
     branches:
       - main
 
-env:
-  JUJU_MODEL: stg-specs-canonical-com
-  JUJU_CONTROLLER: juju-controller-36-staging-ps6
-  JUJU_VERSION: 3.6/stable
+## See ~/.vaultrc in your Juju model
+## Environment variables:
+# WEBSITE_URL (url)
+# JUJU_MODEL (string)
+# JUJU_CONTROLLER (string)
+# JUJU_VERSION (string)
+# VAULT_ADDR (url)
+# VAULT_SECRET_PATH_ROLE (relative path)
+# VAULT_SECRET_PATH_COMMON (relative path)
+#
+## Secrets:
+#  VAULT_APPROLE_RILE_ID (uuid)
+#  VAULT_APPROLE_SECRET_ID (uuid)
 
-  # see ~/.vaultrc in your Juju model
-  VAULT_ADDR: https://vault.admin.canonical.com:8200
-  VAULT_SECRET_PATH_ROLE: secret/prodstack6/roles/stg-specs-canonical-com
-  VAULT_SECRET_PATH_COMMON: secret/prodstack6/juju/common
-  # Secrets:
-  #  VAULT_APPROLE_RILE_ID (uuid)
-  #  VAULT_APPROLE_SECRET_ID (uuid)
+env:
+  DEPLOYMENT_ENV: ${{ github.event.inputs.environment || 'Staging' }}
+  CHARM_BUILD_NAME: ${{ github.event.repository.name }}-${{ github.sha }}.charm
+  ROCK_BUILD_NAME: ${{ github.event.repository.name }}-${{ github.sha }}.rock
 
 jobs:
-  rockcraft-pack:
+  commit-check:
     runs-on: ubuntu-latest
+    outputs:
+      REF: ${{ steps.check-branch.outputs.ref }}
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      - name: Check branch
+        id: check-branch
+        run: |
+          # make sure that the commit sha is from the main branch
+          # otherwise, fail the workflow
+          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
+            if [ "${{ github.event.inputs.commit }}" == "HEAD" ]; then
+              echo "ref=main" >> $GITHUB_OUTPUT
+            else
+              echo "ref=${{ github.event.inputs.commit }}" >> $GITHUB_OUTPUT
+              is_main=$(git branch -r --contains ${{ github.event.inputs.commit }} | grep -c main)
+                if [ $is_main -eq 0 ]; then
+                  echo "Commit is not from the main branch"
+                  echo -e "> [!WARNING]\n> Commit is not from the main branch" >> $GITHUB_STEP_SUMMARY
+                  exit 1
+                fi
+            fi
+          else
+            echo "ref=${GITHUB_SHA}" >> $GITHUB_OUTPUT
+          fi
+
+  rockcraft-pack:
+    runs-on:
+      [self-hosted, self-hosted-linux-amd64-jammy-private-endpoint-medium]
+    needs: commit-check
+    outputs:
+      private_image_url: ${{ steps.image_url.outputs.private_image_url }}
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
         with:
           fetch-depth: 0
+          ref: ${{ needs.commit-check.outputs.REF }}
+
+      # Cache the rock file for production rollout
+      - name: Cache rock
+        id: rock-cache
+        uses: actions/cache@v4
+        with:
+          path: ./*.rock
+          key: ${{ runner.os}}-rock
 
       - name: Setup LXD
+        if: steps.rock-cache.outputs.cache-hit != 'true'
         uses: canonical/setup-lxd@main
 
       - name: Install rockcraft
@@ -36,6 +96,7 @@ jobs:
           sudo snap install --classic rockcraft
 
       - name: Pack project
+        if: steps.rock-cache.outputs.cache-hit != 'true'
         id: rockcraft-pack
         run: |
           sudo rockcraft pack  -v
@@ -43,32 +104,46 @@ jobs:
       - name: Upload rock file
         uses: actions/upload-artifact@v4
         with:
-          name: ${{ env.JUJU_MODEL }}.rock
+          name: ${{ env.ROCK_BUILD_NAME }}
           path: ./*.rock
 
       - name: Set image URL
         id: image_url
         run: |
           IMAGE_URL=ghcr.io/${{ github.repository }}:$(date +%s)-${GITHUB_SHA:0:7}
-          echo "rock_file_url=$IMAGE_URL" >> $GITHUB_OUTPUT
           echo -e "> [!NOTE]\n> Rockcraft OCI image: $IMAGE_URL" >> $GITHUB_STEP_SUMMARY
-
+          echo $DOCKERHUB_MIRROR
+          PRIVATE_IMAGE_URL=10.142.8.140:5001/${{ github.repository }}:$(date +%s)-${GITHUB_SHA:0:7}
+          echo "ghcr_image_url=$IMAGE_URL" >> $GITHUB_OUTPUT
+          echo "private_image_url=$PRIVATE_IMAGE_URL" >> $GITHUB_OUTPUT
       - name: Push to GHCR
+        env:
+          PS6_REGISTRY_CA: ${{ vars.PS6_REGISTRY_CA }}
+          PS6_REGISTRY_CERTIFICATE: ${{ vars.PS6_REGISTRY_CERTIFICATE }}
+          PS6_REGISTRY_KEY: ${{ vars.PS6_REGISTRY_KEY }}
         run: |
-          skopeo --insecure-policy copy oci-archive:$(ls *.rock) docker://${{ steps.image_url.outputs.rock_file_url }} --dest-creds ${{ github.repository_owner }}:${{ secrets.GITHUB_TOKEN }}
+          echo "Pushing to GHCR.."
+          rockcraft.skopeo --insecure-policy copy oci-archive:$(ls *.rock) docker://${{ steps.image_url.outputs.ghcr_image_url }} --dest-creds ${{ github.repository_owner }}:${{ secrets.GITHUB_TOKEN }}
+
+          echo "Pushing to private registry.."
+          mkdir cert
+          echo "$PS6_REGISTRY_KEY" > cert/client.key
+          echo "$PS6_REGISTRY_CERTIFICATE" > cert/client.cert
+          echo "$PS6_REGISTRY_CA" > cert/ca.crt
+          env -i no_proxy=10.142.8.140 /snap/rockcraft/current/bin/skopeo --insecure-policy copy oci-archive:$(ls *.rock) docker://${{ steps.image_url.outputs.private_image_url }} --dest-cert-dir cert --dest-username admin --dest-password password
 
   charmcraft-pack:
     runs-on: ubuntu-latest
-    outputs:
-      charm_file: ${{ steps.charmcraft-pack.outputs.charm_file }}
-
+    needs: commit-check
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
         with:
           fetch-depth: 0
+          ref: ${{ needs.commit-check.outputs.REF }}
 
-      - name: Cache charm directory
+      # This pack task takes a while with less likely to change files
+      - name: Cache charm
         id: charm-cache
         uses: actions/cache@v4
         with:
@@ -94,7 +169,7 @@ jobs:
         uses: actions/upload-artifact@v4
         id: charm-upload
         with:
-          name: ${{ env.JUJU_MODEL }}.charm
+          name: ${{ env.CHARM_BUILD_NAME }}
           path: ./*.charm
 
       - name: Set charm URL
@@ -107,32 +182,41 @@ jobs:
           fi
 
   deploy:
-    needs: [rockcraft-pack, charmcraft-pack]
+    needs: [commit-check, rockcraft-pack, charmcraft-pack]
     runs-on:
       [self-hosted, self-hosted-linux-amd64-jammy-private-endpoint-medium]
-
+    environment:
+      name: ${{ inputs.environment || 'Staging' }}
+      url: ${{ vars.WEBSITE_URL }}
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
         with:
           fetch-depth: 0
+          ref: ${{ needs.commit-check.outputs.REF }}
 
       - name: Install juju
         run: |
-          sudo snap install --classic --channel=$JUJU_VERSION juju
+          sudo snap install --channel=${{ vars.JUJU_VERSION }} juju
           sudo snap install --classic vault
 
-      - name: Download rock file
-        uses: actions/download-artifact@v4
-        with:
-          name: ${{ env.JUJU_MODEL }}.rock
+      - name: Running env
+        run: |
+          echo "${{ env.DEPLOYMENT_ENV }}"
 
-      - name: Download charm file
+      - name: Download Charm Artifact
         uses: actions/download-artifact@v4
         with:
-          name: ${{ env.JUJU_MODEL }}.charm
+          name: ${{ env.CHARM_BUILD_NAME }}
 
       - name: Configure Vault and Juju
+        # TODO: remove condition once production env is ready
+        if: inputs.environment != 'Production'
+        env:
+          VAULT_ADDR: ${{ vars.VAULT_ADDR }}
+          VAULT_SECRET_PATH_ROLE: ${{ vars.VAULT_SECRET_PATH_ROLE }}
+          VAULT_SECRET_PATH_COMMON: ${{ vars.VAULT_SECRET_PATH_COMMON }}
+          JUJU_CONTROLLER: ${{ vars.JUJU_CONTROLLER }}
         run: |
           export TF_VAR_login_approle_role_id=${{ secrets.VAULT_APPROLE_ROLE_ID }}
           export TF_VAR_login_approle_secret_id=${{ secrets.VAULT_APPROLE_SECRET_ID }}
@@ -144,7 +228,12 @@ jobs:
           printf "controllers:\n  $JUJU_CONTROLLER:\n    user: %s\n    password: %s\n" "$USERNAME" "$PASSWORD" > ~/.local/share/juju/accounts.yaml
 
       - name: Deploy charm
+        # TODO: remove condition once production env is ready
+        if: inputs.environment != 'Production'
+        env:
+          JUJU_MODEL: ${{ vars.JUJU_MODEL }}
         run: |
           export JUJU_MODEL=admin/$JUJU_MODEL
           echo "Deploying to $JUJU_MODEL"
-          juju status --relations
+          ls -lha
+          juju refresh specs-canonical-com --path=./$CHARM_FILE --resource app-image=${{ needs.rockcraft-pack.outputs.private_image_url}}
